import Link from "next/link";
import { Suspense } from "react";
import { notFound } from "next/navigation";
import { ArrowLeft, User, CarFront, Calendar, Wallet } from "lucide-react";
import { requireAgency } from "@/lib/auth/session";
import { getContractCritical } from "@/lib/services/contracts";
import { ContractSecondarySections } from "./secondary-sections";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/badge";
import { formatCurrency, formatDate } from "@/lib/utils";
import { CONTRACT_STATUS } from "@/lib/labels";
import { WhatsAppLink } from "@/components/whatsapp-link";
import type { ContractCritical } from "@/lib/services/contracts";

function fuel(level: number | null) { return level === null ? "—" : `${level}/8`; }
function ContractCriticalSkeleton() { return <div className="space-y-6" aria-label="Chargement du dossier"><div className="h-20 animate-pulse rounded-xl bg-muted/60" /><div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><div className="h-36 animate-pulse rounded-xl bg-muted/60" /><div className="h-36 animate-pulse rounded-xl bg-muted/60" /><div className="h-36 animate-pulse rounded-xl bg-muted/60" /></div><div className="h-44 animate-pulse rounded-xl bg-muted/60" /></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-0.5 text-sm">{value}</p></div>; }
function getNextAction(c: ContractCritical, ctx: any) { const preparation=c.preparation, checkout=c.checkout, checkin=c.checkin, balance=c.financials.amountDue, canWrite=["AGENCY_OWNER","MANAGER","AGENT"].includes(ctx.membership.roleKey), canRecordPayment=["AGENCY_OWNER","MANAGER","ACCOUNTANT"].includes(ctx.membership.roleKey), deposit=c.deposit; if (["CLOSED","CANCELLED"].includes(c.status)) return null; if(c.status==="DRAFT") return {label:"Préparer et démarrer la location",href:"#preparation",hint:"Vérifiez les signatures et le véhicule avant la remise."}; if(c.status==="ACTIVE"&&preparation?.status!=="READY"&&!checkout) return {label:"Préparer le véhicule",href:"#preparation",hint:"Validez le nettoyage, le carburant et les documents avant la remise."}; if(!checkout) return {label:"Remettre le véhicule",href:"#check-out",hint:"Saisissez le kilométrage, le carburant et les photos de départ."}; if(!checkin||checkin.status!=="FINALIZED") return {label:"Enregistrer le retour",href:"#check-in",hint:"Faites l’état des lieux et révisez les charges."}; if(balance>0) return canRecordPayment?{label:"Régler le solde",href:`/agency/payments/new?contract=${c.id}`,hint:`Il reste ${formatCurrency(balance)} à encaisser.`}:{label:"Solde à encaisser",href:"#finances",hint:`Il reste ${formatCurrency(balance)} à encaisser par un responsable.`}; if(deposit&&!(["REFUNDED","CLOSED"].includes(deposit.status))) return canRecordPayment?{label:"Régler la caution",href:"#caution",hint:"Déduisez les frais éventuels puis remboursez le reliquat."}:{label:"Caution à régler",href:"#caution",hint:"Le responsable financier doit régler la caution."}; return c.status==="ACTIVE"&&canWrite?{label:"Clôturer la location",href:"#cloture",hint:"Le retour et le règlement sont prêts à être clôturés."}:null; }
function progressIndex(c: ContractCritical) { const checkin=c.checkin, checkout=c.checkout, preparation=c.preparation, balance=c.financials.amountDue, deposit=c.deposit; return c.status==="CLOSED"?7:checkin?.status==="FINALIZED"?(balance>0||(deposit&&!(["REFUNDED","CLOSED"].includes(deposit.status)))?6:7):checkout?4:preparation?.status==="READY"?3:preparation?2:c.status==="ACTIVE"?1:0; }

export default async function ContractDetailPage({ params }: { params: Promise<{ id: string }> }) {
 const ctx=await requireAgency(); const {id}=await params; const c=await getContractCritical(id,ctx.membership.agencyId); if(!c) notFound(); const nextAction=getNextAction(c,ctx); const steps=["Réservé","Confirmé","Préparation","Prêt","Loué","Retour","Règlement","Clôturé"]; const current=progressIndex(c);
 return <><div className="space-y-6 print:hidden">
  <div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">Dossier de location</p><h2 className="text-xl font-semibold">{ctx.membership.agencyName}</h2><p className="text-xs text-muted-foreground">Les détails complémentaires se chargent après les informations essentielles.</p></div><div className="text-left text-xs text-muted-foreground sm:text-right"><p>Contrat {c.contract_number}</p><p>Généré le {formatDate(new Date().toISOString())}</p></div></div>
  <Button asChild variant="ghost" size="sm"><Link href="/agency/contracts"><ArrowLeft /> Retour aux contrats</Link></Button>
  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-3"><h1 className="font-mono text-2xl font-semibold tracking-tight">{c.contract_number}</h1><StatusBadge meta={CONTRACT_STATUS[c.status]} /></div><p className="text-sm text-muted-foreground">{formatDate(c.start_date)} → {formatDate(c.end_date)}{c.reservationRef&&<> · depuis réservation {c.reservationRef}</>}</p></div>{nextAction&&<Button asChild size="sm"><Link href={nextAction.href}>{nextAction.label}</Link></Button>}</div>
  <div aria-label="Progression de la location" className="overflow-x-auto rounded-2xl border border-border/70 bg-card/60 px-4 py-4"><div className="flex min-w-[680px] items-start">{steps.map((step,index)=><div key={step} className="flex flex-1 items-start"><div className="flex min-w-0 flex-col items-center gap-2 text-center"><span className={`flex size-7 items-center justify-center rounded-full border text-xs font-semibold ${index<=current?"border-primary bg-primary text-primary-foreground":"border-border bg-background text-muted-foreground"}`}>{index+1}</span><span className={`text-[11px] font-medium ${index<=current?"text-foreground":"text-muted-foreground"}`}>{step}</span></div>{index<steps.length-1&&<span className={`mt-3 h-px flex-1 ${index<current?"bg-primary":"bg-border"}`} />}</div>)}</div></div>
  {nextAction&&<Card className="border-primary/30 bg-primary/5"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Prochaine action</p><p className="text-sm text-muted-foreground">{nextAction.hint}</p></div><Button asChild size="sm"><Link href={nextAction.href}>{nextAction.label}</Link></Button></CardContent></Card>}
  <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><User className="size-4" /> Client</CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><Link href={`/agency/customers/${c.customer.id}`} className="font-medium hover:underline">{c.customer.name}</Link>{c.customer.phone&&<p className="text-muted-foreground">{c.customer.phone}</p>}{c.customer.email&&<p className="text-muted-foreground">{c.customer.email}</p>}<p className="text-xs text-muted-foreground">Pièce : {c.customer.id_number??"—"} · Permis : {c.customer.driver_license_number??"—"}</p><WhatsAppLink phone={c.customer.whatsapp??c.customer.phone} message={`Bonjour ${c.customer.name}, votre contrat ${c.contract_number} est disponible.`}/></CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CarFront className="size-4" /> Véhicule</CardTitle></CardHeader><CardContent className="space-y-1 text-sm"><Link href={`/agency/fleet/${c.vehicle.id}`} className="font-medium hover:underline">{c.vehicle.label}</Link><p className="font-mono text-muted-foreground">{c.vehicle.plate}</p><p className="text-xs text-muted-foreground">Départ : {c.start_mileage??"—"} km · carburant {fuel(c.fuel_level_start)}</p><p className="text-xs text-muted-foreground">Prise en charge : {c.pickupLocation??"—"} · retour : {c.returnLocation??"—"}</p></CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Calendar className="size-4" /> État du véhicule</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><Info label="Km départ" value={c.start_mileage?c.start_mileage.toLocaleString("fr-MA"):"—"}/><Info label="Km retour" value={c.end_mileage?c.end_mileage.toLocaleString("fr-MA"):"—"}/><Info label="Carburant départ" value={fuel(c.fuel_level_start)}/><Info label="Carburant retour" value={fuel(c.fuel_level_end)}/></CardContent></Card>
  </div>
  <Card id="finances-summary"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Wallet className="size-4" /> Résumé financier</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4 sm:grid-cols-4"><Info label="Total contrat" value={formatCurrency(c.financials.grandTotal)}/><Info label="Charges retour" value={formatCurrency(c.financials.returnChargesTotal)}/><Info label="Loyers encaissés" value={formatCurrency(c.financials.rentalPaidTotal)}/><Info label="Solde à régler" value={formatCurrency(c.financials.amountDue)}/><div className="col-span-2 sm:col-span-4"><div className={`rounded-md border p-3 text-sm ${c.financials.amountDue>0?"border-amber-300 bg-amber-50 dark:bg-amber-950/30":"border-green-300 bg-green-50 dark:bg-green-950/30"}`}>{c.financials.amountDue>0?<>Solde restant à régler : <strong>{formatCurrency(c.financials.amountDue)}</strong></>:<>Contrat entièrement réglé.</>}</div></div></CardContent></Card>
  {c.deposit&&<Card id="caution-summary"><CardHeader><CardTitle className="text-base">Résumé de la caution</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Info label="Requise" value={formatCurrency(Number(c.deposit.required_amount))}/><Info label="Reçue" value={formatCurrency(Number(c.deposit.received_amount))}/><Info label="Détenue" value={formatCurrency(Number(c.deposit.held_amount))}/><Info label="Disponible" value={formatCurrency(c.financials.depositAvailable)}/></CardContent></Card>}
 </div><Suspense fallback={<ContractCriticalSkeleton />}><ContractSecondarySections id={id} agencyId={ctx.membership.agencyId} ctx={ctx}/></Suspense></>;
}
